In [19]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [20]:
datasets = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML/lab2/Data_for_Categorical_Values.csv')
print("Data : \n", datasets)
print("\n=======================================n")
print("Data Statictic : ", datasets.describe())

Data : 
     Country  Age  Salary Purchased
0    France   44   72000        No
1     Spain   27   48000       Yes
2   Germany   30   54000        No
3     Spain   38   61000        No
4   Germany   40   68000       Yes
5    France   35   58000       Yes
6     Spain   39   52000        No
7    France   48   79000       Yes
8   Germany   50   83000        No
9    France   37   67000       Yes
10    Spain   45   55000        No

=======================================n
Data Statictic :               Age        Salary
count  11.000000     11.000000
mean   39.363636  63363.636364
std     7.131237  11386.594989
min    27.000000  48000.000000
25%    36.000000  54500.000000
50%    39.000000  61000.000000
75%    44.500000  70000.000000
max    50.000000  83000.000000


In [21]:
X = datasets.iloc[:, :-1].values
Y = datasets.iloc[:, -1].values

print("X : ",X)
print("Y : ",Y)

X :  [['France' 44 72000]
 ['Spain' 27 48000]
 ['Germany' 30 54000]
 ['Spain' 38 61000]
 ['Germany' 40 68000]
 ['France' 35 58000]
 ['Spain' 39 52000]
 ['France' 48 79000]
 ['Germany' 50 83000]
 ['France' 37 67000]
 ['Spain' 45 55000]]
Y :  ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No']


In [22]:
lable_encoder = LabelEncoder()
X[: ,0] = lable_encoder.fit_transform(X[: ,0])
print("\nInput : \n",X)


Input : 
 [[0 44 72000]
 [2 27 48000]
 [1 30 54000]
 [2 38 61000]
 [1 40 68000]
 [0 35 58000]
 [2 39 52000]
 [0 48 79000]
 [1 50 83000]
 [0 37 67000]
 [2 45 55000]]


In [24]:
dummy_var = pd.get_dummies(datasets['Country'])
print("\nDummy Data : \n",dummy_var)


datasets = datasets.drop(['Country','Purchased'],axis=1)
print("\nIntermidiate Dataset : \n",datasets)
datasets = pd.concat([dummy_var,datasets],axis=1)
print("\nFinal Dataset : \n",datasets)



Dummy Data : 
     France  Germany  Spain
0        1        0      0
1        0        0      1
2        0        1      0
3        0        0      1
4        0        1      0
5        1        0      0
6        0        0      1
7        1        0      0
8        0        1      0
9        1        0      0
10       0        0      1

Intermidiate Dataset : 
     Age  Salary
0    44   72000
1    27   48000
2    30   54000
3    38   61000
4    40   68000
5    35   58000
6    39   52000
7    48   79000
8    50   83000
9    37   67000
10   45   55000

Final Dataset : 
     France  Germany  Spain  Age  Salary
0        1        0      0   44   72000
1        0        0      1   27   48000
2        0        1      0   30   54000
3        0        0      1   38   61000
4        0        1      0   40   68000
5        1        0      0   35   58000
6        0        0      1   39   52000
7        1        0      0   48   79000
8        0        1      0   50   83000
9        1        0    