In [58]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()

In [59]:
print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)
iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [60]:
 from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(iris.data,iris.target, test_size = 0.30, random_state = 10)

In [61]:
import numpy as np
gnb = GaussianNB() 
gnb.fit(data_train, target_train) 
target_pred = gnb.predict(data_test)

In [62]:
from sklearn import metrics 
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [63]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [64]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


In [65]:
#Excersize
#Task 1: Try the algo on Dataset2 - OneHotEncoding of features: and Train test Division 75%-25%
import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [66]:
dataset= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML/lab3/PracticeDataSets/Dataset2.csv')
print("\n\nData: \n",dataset)



Data: 
    Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [67]:
data= pd.get_dummies(dataset,columns=['Outlook','Temp','Humidity','Wind','Class'])
data= data.drop(['Class_N'],axis=1)
print("One Hot Encoder:\n\n",data)

One Hot Encoder:

     Outlook_O  Outlook_R  Outlook_S  ...  Wind_F  Wind_T  Class_Y
0           0          1          0  ...       1       0        0
1           0          1          0  ...       0       1        0
2           1          0          0  ...       1       0        1
3           0          0          1  ...       1       0        0
4           0          0          1  ...       1       0        1
5           0          0          1  ...       0       1        1
6           1          0          0  ...       0       1        1
7           0          1          0  ...       1       0        1
8           0          1          0  ...       1       0        1
9           0          0          1  ...       1       0        1
10          0          1          0  ...       0       1        1
11          1          0          0  ...       0       1        1
12          1          0          0  ...       1       0        1
13          0          0          1  ...       0       1 

In [68]:
#train-test split data 75%-25%
X= data.iloc[:,:-1]
Y= data.iloc[:,-1]
data_train, data_test, target_train, target_test = train_test_split(X, Y, test_size = 0.25, random_state = 77)

In [69]:
model = GaussianNB()

#Train the model using the training sets
model.fit(data_train, target_train)

#Predict the response for test dataset
target_pred =model.predict(data_test)

In [70]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.75


In [71]:
confusion_matrix(target_test, target_pred)

array([[1, 0],
       [1, 2]])

In [72]:
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print(f'precision: {precision}')
print(f'recall: {recall}')

precision: [0.5 1. ]
recall: [1.         0.66666667]


In [73]:
#Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?
output1= model.predict([[0,1,0,0,0,1,0,0,1,1,0]])
print(f'Play: {output1}')
#Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True'
output2= model.predict([[0,0,1,1,0,0,1,0,0,0,1]])
print(f'Play: {output2}')

Play: [0]
Play: [1]


In [74]:
#Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 80%-20%
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
wine= datasets.load_wine()

In [75]:
print("Features: ", wine.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", wine.target_names)
# print data(feature)shape & target shape
print("\nData Shape: ",wine.data.shape)
print("\nTarget Shape:",wine.target.shape)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']

Data Shape:  (178, 13)

Target Shape: (178,)


In [76]:
data_train, data_test, target_train, target_test = train_test_split(X, Y, test_size = 0.20, random_state = 77)

In [77]:
gnb= GaussianNB()
model.fit(data_train, target_train)
target_pred= model.predict(data_test)

In [78]:
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))
confusion_matrix(target_test, target_pred)

Accuracy: 1.0


array([[1, 0],
       [0, 2]])

In [79]:
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print(f'precision: {precision}')
print(f'recall: {recall}')

precision: [1. 1.]
recall: [1. 1.]
